//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fm2ModelContainer : DbContext
    {
        public Fm2ModelContainer()
            : base("name=Fm2ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Weights> Weights { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<PositionLookup> PositionLookups { get; set; }
        public virtual DbSet<Tactic> Tactics { get; set; }
    }
}
