//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weights
    {
        public int Id { get; set; }
        public string Attribute { get; set; }
        public decimal Weight { get; set; }
        public int TacticId { get; set; }
    
        public virtual Tactic Tactic { get; set; }
    }
}
